name: Build API

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_api:
        name: Build API
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build API
              run: npx -y open-judge build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./dist"
                  publish_branch: "gh-pages"
